sudo: false
language: java
jdk: oraclejdk8
script: mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: aWAANkzF6IUzQrXrq4bRZZgTTIFfNIOe0PHB4eM/Y6I+0TAZnP2AjnQtmeT/eFiOm6ucwTJx9rdEJvLWxTIJml5TveqwH5OHaH6e3PC7jq7KDaVJls/CXJ89mngKtM480EYY2pwQzu2195h61wocZpYxqOlPLJG9RBIlptiobL7+Dd0sSglvAQJ7HvxfpxYWEy66yJrkNoJZvuzwnIOTWhIYAPnmkwezIPTMR/7bHLfLfJOpbrjTmaF5Rv0UDb2yRZnLiegRBfafp3ObA92cWqfpYB1Z4BZrC9/V9q08vjxRvcnnFCkmSgpTzOY4HH1Vqwc7bARmuzqDEN/0jDL1YN3fXhx3gDFjlFuyFGD+v/bsyR/ugmYRG8lno4pjudPPfLddUZJk/NgLfjJ4dA7YRDCpzJ5JLXPrPLw41LpiuZMO0PpeY4B5Tg7OkI+IXB+9StU4bHqw8As1C38GZp30E+QZkw3L7KOJ8scElOpr2/LzqF4Co6SCM+3Dm+CaY+nC93pbX09R0p0ts97SpnNv9ldRTc6TgAhhRasdOS8FU64qcYFeOT05aD5Xv8lxkxxrdxk6h1kunVEQjuf7tDAXM8fGE1/8NEMCGU4MNGFu2YuSzNNhlDGrgGV8httHwM0J67uppxk5HxEe6py4McSh2htuoD8eZmbeVG3QhuzGUxk=
  app: motherbook
  on:
    repo: anderscodes/mother_acebook
